name: Create push event

on: push

jobs:
  push-event:
    runs-on: ubuntu-latest
    name: Record push event
    steps:
      - name: Test deployment marker
        uses: ./
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          
          
