name: Create push event

on: push

jobs:
  push-event:
    runs-on: ubuntu-latest
    name: NR push event job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Post push event
        uses: ./
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          insertKey: ${{ secrets.NEW_RELIC_INSIGHTS_INSERT_KEY }}
          
          
