name: Create push event

on: [push]

jobs:
  push-event:
    runs-on: ubuntu-latest
    name: NR push event job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: dump context three
        env: 
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Send push event
        uses: ./
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          insertKey: ${{ secrets.NEW_RELIC_INSIGHTS_INSERT_KEY }}
          commitMessage: ${{ github.event.head_commit.message }}
          commitTimestamp: ${{ github.event.pushed_at }}
          user: ${{ github.event.pusher.name }}
          email: ${{ github.event.pusher.email }}
          
          
