name: Test Suite

on:
  pull_request:
  push:
    branches:
      - master

jobs:
#  should_fail_test:
#    runs-on: ubuntu-latest
#    name: Should Fail Test
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Test deployment marker
#        uses: ./
#        with:
#          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
#          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
#          applicationId: 0
#          revision: "deployment-marker-action-should-fail-test:${{ github.ref }}"

  basic_test:
    runs-on: ubuntu-latest
    name: Basic Usage Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test deployment marker
        uses: ./
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          applicationId: ${{ secrets.APPLICATION_ID }}
          revision: "deployment-marker-action-basic-test:${{ github.ref }}"

  all_inputs_test:
    runs-on: ubuntu-latest
    name: All Inputs Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test deployment marker
        uses: ./
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          applicationId: ${{ secrets.APPLICATION_ID }}
          revision: "deployment-marker-action-all-input-test-${{ github.sha }}"
          user: "hardcoded-test-username"                             # optional
          region: US                                                  # optional

